pipeline {
    agent any

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/CloudDevops-Tech/CICD.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Day1_Terraform_Basic_Config') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Day1_Terraform_Basic_Config') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Day1_Terraform_Basic_Config') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Approval') {
            steps {
                input "Do you want to apply changes?"
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Day1_Terraform_Basic_Config') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}