name: CICD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  git-job:
    name: Git Job
    runs-on: [self-hosted, git-runner]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Git Server
        run: |
          echo "Running on Git Runner"
          hostname
          pwd
          ls -la

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

  terraform-job:
    name: Terraform Job
    runs-on: [self-hosted, terraform-runner]
    needs: git-job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Terraform Server
        run: |
          echo "Running on Terraform Runner"
          hostname
          pwd
          ls -la

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve