pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/CloudDevops-Tech/CICD.git'
            }
        }

        stage('Deploy to Ubuntu EC2') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/pythonkey.pem ubuntu@13.201.64.222 << 'EOF'

                cd /home/ubuntu/app || git clone https://github.com/CloudDevops-Tech/CICD.git /home/ubuntu/app
                cd /home/ubuntu/app

                git pull origin main

                pip3 install -r requirements.txt

                pkill -f app.py || true

                nohup python3 app.py > output.log 2>&1 &

                EOF
                '''
            }
        }
    }
}